apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m7bmlpzh3-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:1a26f6054ca6240b4e224d10e7072addfa8fb7da@sha256:fe1455a1fb53c5b35368f3420d85f239d39d9e48035c4850f5d7b8444bd18a71
          name: container-image
